language: java
script: bash build --debug
# We need sudo to install dependencies (apt-get)
sudo: false

addons:
    apt:
        packages:
            - curl
            - gcc
            - make
            - maven
            - nodejs
            - openjdk-7-jdk
            - openjdk-7-jre
cache:
    directories:
        - $HOME/.m2

after_success:
    - bash <(curl -s https://codecov.io/bash)
