language: java

sudo: false

addons:
    apt:
        packages:
            - make
            - maven
            - openjdk-7-jdk
            - openjdk-7-jre

cache:
    directories:
        - $HOME/.m2

script: build.sh
